part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const SPLASH = _Paths.SPLASH;
  static const LOGIN_TYPE = _Paths.LOGIN_TYPE;
  static const LOGIN = _Paths.LOGIN;
  static const OTP = _Paths.OTP;
  static const USER_SIGNUP = _Paths.USER_SIGNUP;
  static const PROVIDER_SIGNUP = _Paths.PROVIDER_SIGNUP;
  static const NAV_BAR = _Paths.NAV_BAR;
  static const HOME = _Paths.HOME;
  static const PROFILE = _Paths.PROFILE;
  static const ADD_PROJECT = _Paths.ADD_PROJECT;
  static const PROJECT_DETAIL = _Paths.PROJECT_DETAIL;
  static const MESSAGES = _Paths.MESSAGES;
  static const CHAT = _Paths.CHAT;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const LOGOUT = _Paths.LOGOUT;
  static const PRIVACY_POLICY = _Paths.PRIVACY_POLICY;
  static const TERMS_CONDITION = _Paths.TERMS_CONDITION;
  static const ABOUT_US = _Paths.ABOUT_US;
  static const MY_ACCOUNT = _Paths.MY_ACCOUNT;
  static const PROJECT_DETAIL_PROPOSAL = _Paths.PROJECT_DETAIL_PROPOSAL;
  static const DOCUMENT = _Paths.DOCUMENT;
  static const NOTIFICATION_SETTING = _Paths.NOTIFICATION_SETTING;
  static const FAQ = _Paths.FAQ;
  static const NOTIFICATIONS = _Paths.NOTIFICATIONS;
  static const EDIT_PROFILE = _Paths.EDIT_PROFILE;
  static const JOBS = _Paths.JOBS;
  static const NEWS = _Paths.NEWS;
  static const SUBSCRIPTION = _Paths.SUBSCRIPTION;
  static const PROVIDERS = _Paths.PROVIDERS;
  static const PROVIDER_PROPOSALS = _Paths.PROVIDER_PROPOSALS;
  static const PROPOSAL_DETAILS = _Paths.PROPOSAL_DETAILS;
  static const NEWS_DETAILS = _Paths.NEWS_DETAILS;
  static const PROVIDER_DETAILS = _Paths.PROVIDER_DETAILS;
  static const PROVIDER_PROFILE = _Paths.PROVIDER_PROFILE;
  static const PROVIDER_NAV_BAR = _Paths.PROVIDER_NAV_BAR;
  static const JOB_DETAILS = _Paths.JOB_DETAILS;
  static const SEARCH_JOB = _Paths.SEARCH_JOB;
}

abstract class _Paths {
  _Paths._();
  static const SPLASH = '/splash';
  static const LOGIN_TYPE = '/login-type';
  static const LOGIN = '/login';
  static const OTP = '/otp';
  static const USER_SIGNUP = '/user-signup';
  static const PROVIDER_SIGNUP = '/provider-signup';
  static const NAV_BAR = '/nav-bar';
  static const HOME = '/home';
  static const PROFILE = '/profile';
  static const ADD_PROJECT = '/add-project';
  static const PROJECT_DETAIL = '/project-detail';
  static const MESSAGES = '/messages';
  static const CHAT = '/chat';
  static const CHANGE_PASSWORD = '/change-password';
  static const LOGOUT = '/logout';
  static const PRIVACY_POLICY = '/privacy-policy';
  static const TERMS_CONDITION = '/terms-condition';
  static const ABOUT_US = '/about-us';
  static const MY_ACCOUNT = '/my-account';
  static const PROJECT_DETAIL_PROPOSAL = '/project-detail-proposal';
  static const DOCUMENT = '/document';
  static const NOTIFICATION_SETTING = '/notification-setting';
  static const FAQ = '/faq';
  static const NOTIFICATIONS = '/notifications';
  static const EDIT_PROFILE = '/edit-profile';
  static const JOBS = '/jobs';
  static const NEWS = '/news';
  static const SUBSCRIPTION = '/subscription';
  static const PROVIDERS = '/providers';
  static const PROVIDER_PROPOSALS = '/provider-proposals';
  static const PROPOSAL_DETAILS = '/proposal-details';
  static const NEWS_DETAILS = '/news-details';
  static const PROVIDER_DETAILS = '/provider-details';
  static const PROVIDER_PROFILE = '/provider-profile';
  static const PROVIDER_NAV_BAR = '/provider-nav-bar';
  static const JOB_DETAILS = '/job-details';
  static const SEARCH_JOB = '/search-job';
}
